//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voyageur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int id { get; set; }
        public int id_ville_depart { get; set; }
        public int id_ville_destination { get; set; }
        public System.DateTime date_depart { get; set; }
        public int id_client { get; set; }
        public System.DateTime date_arrive { get; set; }
        public int nbr { get; set; }
        public System.DateTime date_destionation { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
    }
}
