//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voyageur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public int id_trajet { get; set; }
        public int id_client { get; set; }
        public System.DateTime date_reservation { get; set; }
        public int nbr { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual trajet trajet { get; set; }
    }
}
